version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: policydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: dev/Dockerfile
    container_name: api_dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/policydb
    depends_on:
      - db

volumes:
  pgdata: